spring.application.name=student-portfolio-backend

# Railway PORT
server.port=${PORT:8083}

# Railway Database (auto provided)
spring.datasource.url=${railway}
spring.datasource.username=${root}
spring.datasource.password=${BQZMkIZOdYkVDfopMgxGYjAYkujStybn}

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
